use std::string::ToString;

#[derive(Debug, PartialEq, Eq)]
#[allow(non_camel_case_types)]
pub enum Command {
    STATUS,
    NEW_SESSION,
    GET_ALL_SESSIONS,
    DELETE_SESSION,
    CLOSE,
    QUIT,
    GET,
    GO_BACK,
    GO_FORWARD,
    REFRESH,
    ADD_COOKIE,
    GET_COOKIE,
    GET_ALL_COOKIES,
    DELETE_COOKIE,
    DELETE_ALL_COOKIES,
    FIND_ELEMENT,
    FIND_ELEMENTS,
    FIND_CHILD_ELEMENT,
    FIND_CHILD_ELEMENTS,
    CLEAR_ELEMENT,
    CLICK_ELEMENT,
    SEND_KEYS_TO_ELEMENT,
    SEND_KEYS_TO_ACTIVE_ELEMENT,
    SUBMIT_ELEMENT,
    UPLOAD_FILE,
    GET_CURRENT_WINDOW_HANDLE,
    W3C_GET_CURRENT_WINDOW_HANDLE,
    GET_WINDOW_HANDLES,
    W3C_GET_WINDOW_HANDLES,
    GET_WINDOW_SIZE,
    W3C_GET_WINDOW_SIZE,
    W3C_GET_WINDOW_POSITION,
    GET_WINDOW_POSITION,
    SET_WINDOW_SIZE,
    W3C_SET_WINDOW_SIZE,
    SET_WINDOW_RECT,
    GET_WINDOW_RECT,
    SET_WINDOW_POSITION,
    W3C_SET_WINDOW_POSITION,
    SWITCH_TO_WINDOW,
    SWITCH_TO_FRAME,
    SWITCH_TO_PARENT_FRAME,
    GET_ACTIVE_ELEMENT,
    W3C_GET_ACTIVE_ELEMENT,
    GET_CURRENT_URL,
    GET_PAGE_SOURCE,
    GET_TITLE,
    EXECUTE_SCRIPT,
    W3C_EXECUTE_SCRIPT,
    W3C_EXECUTE_SCRIPT_ASYNC,
    GET_ELEMENT_TEXT,
    GET_ELEMENT_VALUE,
    GET_ELEMENT_TAG_NAME,
    SET_ELEMENT_SELECTED,
    IS_ELEMENT_SELECTED,
    IS_ELEMENT_ENABLED,
    IS_ELEMENT_DISPLAYED,
    GET_ELEMENT_LOCATION,
    GET_ELEMENT_LOCATION_ONCE_SCROLLED_INTO_VIEW,
    GET_ELEMENT_SIZE,
    GET_ELEMENT_RECT,
    GET_ELEMENT_ATTRIBUTE,
    GET_ELEMENT_PROPERTY,
    GET_ELEMENT_VALUE_OF_CSS_PROPERTY,
    ELEMENT_EQUALS,
    SCREENSHOT,
    ELEMENT_SCREENSHOT,
    IMPLICIT_WAIT,
    EXECUTE_ASYNC_SCRIPT,
    SET_SCRIPT_TIMEOUT,
    SET_TIMEOUTS,
    MAXIMIZE_WINDOW,
    W3C_MAXIMIZE_WINDOW,
    GET_LOG,
    GET_AVAILABLE_LOG_TYPES,
    FULLSCREEN_WINDOW,
    MINIMIZE_WINDOW,

    // Alerts
    DISMISS_ALERT,
    W3C_DISMISS_ALERT,
    ACCEPT_ALERT,
    W3C_ACCEPT_ALERT,
    SET_ALERT_VALUE,
    W3C_SET_ALERT_VALUE,
    GET_ALERT_TEXT,
    W3C_GET_ALERT_TEXT,
    SET_ALERT_CREDENTIALS,

    // Advanced user interactions
    W3C_ACTIONS,
    W3C_CLEAR_ACTIONS,
    CLICK,
    DOUBLE_CLICK,
    MOUSE_DOWN,
    MOUSE_UP,
    MOVE_TO,

    // Screen Orientation
    SET_SCREEN_ORIENTATION,
    GET_SCREEN_ORIENTATION,

    // Touch Actions
    SINGLE_TAP,
    TOUCH_DOWN,
    TOUCH_UP,
    TOUCH_MOVE,
    TOUCH_SCROLL,
    DOUBLE_TAP,
    LONG_PRESS,
    FLICK,

    // HTML 5
    EXECUTE_SQL,

    GET_LOCATION,
    SET_LOCATION,

    GET_APP_CACHE,
    GET_APP_CACHE_STATUS,
    CLEAR_APP_CACHE,

    GET_LOCAL_STORAGE_ITEM,
    REMOVE_LOCAL_STORAGE_ITEM,
    GET_LOCAL_STORAGE_KEYS,
    SET_LOCAL_STORAGE_ITEM,
    CLEAR_LOCAL_STORAGE,
    GET_LOCAL_STORAGE_SIZE,

    GET_SESSION_STORAGE_ITEM,
    REMOVE_SESSION_STORAGE_ITEM,
    GET_SESSION_STORAGE_KEYS,
    SET_SESSION_STORAGE_ITEM,
    CLEAR_SESSION_STORAGE,
    GET_SESSION_STORAGE_SIZE,

    // Mobile
    GET_NETWORK_CONNECTION,
    SET_NETWORK_CONNECTION,
    CURRENT_CONTEXT_HANDLE,
    CONTEXT_HANDLES,
    SWITCH_TO_CONTEXT,
}

impl ToString for Command {
    fn to_string(&self) -> String {
        match *self {
            Command::STATUS => "status",
            Command::NEW_SESSION => "newSession",
            Command::GET_ALL_SESSIONS => "getAllSessions",
            Command::DELETE_SESSION => "deleteSession",
            Command::CLOSE => "close",
            Command::QUIT => "quit",
            Command::GET => "get",
            Command::GO_BACK => "goBack",
            Command::GO_FORWARD => "goForward",
            Command::REFRESH => "refresh",
            Command::ADD_COOKIE => "addCookie",
            Command::GET_COOKIE => "getCookie",
            Command::GET_ALL_COOKIES => "getCookies",
            Command::DELETE_COOKIE => "deleteCookie",
            Command::DELETE_ALL_COOKIES => "deleteAllCookies",
            Command::FIND_ELEMENT => "findElement",
            Command::FIND_ELEMENTS => "findElements",
            Command::FIND_CHILD_ELEMENT => "findChildElement",
            Command::FIND_CHILD_ELEMENTS => "findChildElements",
            Command::CLEAR_ELEMENT => "clearElement",
            Command::CLICK_ELEMENT => "clickElement",
            Command::SEND_KEYS_TO_ELEMENT => "sendKeysToElement",
            Command::SEND_KEYS_TO_ACTIVE_ELEMENT => "sendKeysToActiveElement",
            Command::SUBMIT_ELEMENT => "submitElement",
            Command::UPLOAD_FILE => "uploadFile",
            Command::GET_CURRENT_WINDOW_HANDLE => "getCurrentWindowHandle",
            Command::W3C_GET_CURRENT_WINDOW_HANDLE => "w3cGetCurrentWindowHandle",
            Command::GET_WINDOW_HANDLES => "getWindowHandles",
            Command::W3C_GET_WINDOW_HANDLES => "w3cGetWindowHandles",
            Command::GET_WINDOW_SIZE => "getWindowSize",
            Command::W3C_GET_WINDOW_SIZE => "w3cGetWindowSize",
            Command::W3C_GET_WINDOW_POSITION => "w3cGetWindowPosition",
            Command::GET_WINDOW_POSITION => "getWindowPosition",
            Command::SET_WINDOW_SIZE => "setWindowSize",
            Command::W3C_SET_WINDOW_SIZE => "w3cSetWindowSize",
            Command::SET_WINDOW_RECT => "setWindowRect",
            Command::GET_WINDOW_RECT => "getWindowRect",
            Command::SET_WINDOW_POSITION => "setWindowPosition",
            Command::W3C_SET_WINDOW_POSITION => "w3cSetWindowPosition",
            Command::SWITCH_TO_WINDOW => "switchToWindow",
            Command::SWITCH_TO_FRAME => "switchToFrame",
            Command::SWITCH_TO_PARENT_FRAME => "switchToParentFrame",
            Command::GET_ACTIVE_ELEMENT => "getActiveElement",
            Command::W3C_GET_ACTIVE_ELEMENT => "w3cGetActiveElement",
            Command::GET_CURRENT_URL => "getCurrentUrl",
            Command::GET_PAGE_SOURCE => "getPageSource",
            Command::GET_TITLE => "getTitle",
            Command::EXECUTE_SCRIPT => "executeScript",
            Command::W3C_EXECUTE_SCRIPT => "w3cExecuteScript",
            Command::W3C_EXECUTE_SCRIPT_ASYNC => "w3cExecuteScriptAsync",
            Command::GET_ELEMENT_TEXT => "getElementText",
            Command::GET_ELEMENT_VALUE => "getElementValue",
            Command::GET_ELEMENT_TAG_NAME => "getElementTagName",
            Command::SET_ELEMENT_SELECTED => "setElementSelected",
            Command::IS_ELEMENT_SELECTED => "isElementSelected",
            Command::IS_ELEMENT_ENABLED => "isElementEnabled",
            Command::IS_ELEMENT_DISPLAYED => "isElementDisplayed",
            Command::GET_ELEMENT_LOCATION => "getElementLocation",
            Command::GET_ELEMENT_LOCATION_ONCE_SCROLLED_INTO_VIEW => {
                "getElementLocationOnceScrolledIntoView"
            }
            Command::GET_ELEMENT_SIZE => "getElementSize",
            Command::GET_ELEMENT_RECT => "getElementRect",
            Command::GET_ELEMENT_ATTRIBUTE => "getElementAttribute",
            Command::GET_ELEMENT_PROPERTY => "getElementProperty",
            Command::GET_ELEMENT_VALUE_OF_CSS_PROPERTY => "getElementValueOfCssProperty",
            Command::ELEMENT_EQUALS => "elementEquals",
            Command::SCREENSHOT => "screenshot",
            Command::ELEMENT_SCREENSHOT => "elementScreenshot",
            Command::IMPLICIT_WAIT => "implicitlyWait",
            Command::EXECUTE_ASYNC_SCRIPT => "executeAsyncScript",
            Command::SET_SCRIPT_TIMEOUT => "setScriptTimeout",
            Command::SET_TIMEOUTS => "setTimeouts",
            Command::MAXIMIZE_WINDOW => "windowMaximize",
            Command::W3C_MAXIMIZE_WINDOW => "w3cMaximizeWindow",
            Command::GET_LOG => "getLog",
            Command::GET_AVAILABLE_LOG_TYPES => "getAvailableLogTypes",
            Command::FULLSCREEN_WINDOW => "fullscreenWindow",
            Command::MINIMIZE_WINDOW => "minimizeWindow",

            // Alerts
            Command::DISMISS_ALERT => "dismissAlert",
            Command::W3C_DISMISS_ALERT => "w3cDismissAlert",
            Command::ACCEPT_ALERT => "acceptAlert",
            Command::W3C_ACCEPT_ALERT => "w3cAcceptAlert",
            Command::SET_ALERT_VALUE => "setAlertValue",
            Command::W3C_SET_ALERT_VALUE => "w3cSetAlertValue",
            Command::GET_ALERT_TEXT => "getAlertText",
            Command::W3C_GET_ALERT_TEXT => "w3cGetAlertText",
            Command::SET_ALERT_CREDENTIALS => "setAlertCredentials",

            // Advanced user interactions
            Command::W3C_ACTIONS => "actions",
            Command::W3C_CLEAR_ACTIONS => "clearActionState",
            Command::CLICK => "mouseClick",
            Command::DOUBLE_CLICK => "mouseDoubleClick",
            Command::MOUSE_DOWN => "mouseButtonDown",
            Command::MOUSE_UP => "mouseButtonUp",
            Command::MOVE_TO => "mouseMoveTo",

            // Screen Orientation
            Command::SET_SCREEN_ORIENTATION => "setScreenOrientation",
            Command::GET_SCREEN_ORIENTATION => "getScreenOrientation",

            // Touch Actions
            Command::SINGLE_TAP => "touchSingleTap",
            Command::TOUCH_DOWN => "touchDown",
            Command::TOUCH_UP => "touchUp",
            Command::TOUCH_MOVE => "touchMove",
            Command::TOUCH_SCROLL => "touchScroll",
            Command::DOUBLE_TAP => "touchDoubleTap",
            Command::LONG_PRESS => "touchLongPress",
            Command::FLICK => "touchFlick",

            // HTML 5
            Command::EXECUTE_SQL => "executeSql",

            Command::GET_LOCATION => "getLocation",
            Command::SET_LOCATION => "setLocation",

            Command::GET_APP_CACHE => "getAppCache",
            Command::GET_APP_CACHE_STATUS => "getAppCacheStatus",
            Command::CLEAR_APP_CACHE => "clearAppCache",

            Command::GET_LOCAL_STORAGE_ITEM => "getLocalStorageItem",
            Command::REMOVE_LOCAL_STORAGE_ITEM => "removeLocalStorageItem",
            Command::GET_LOCAL_STORAGE_KEYS => "getLocalStorageKeys",
            Command::SET_LOCAL_STORAGE_ITEM => "setLocalStorageItem",
            Command::CLEAR_LOCAL_STORAGE => "clearLocalStorage",
            Command::GET_LOCAL_STORAGE_SIZE => "getLocalStorageSize",

            Command::GET_SESSION_STORAGE_ITEM => "getSessionStorageItem",
            Command::REMOVE_SESSION_STORAGE_ITEM => "removeSessionStorageItem",
            Command::GET_SESSION_STORAGE_KEYS => "getSessionStorageKeys",
            Command::SET_SESSION_STORAGE_ITEM => "setSessionStorageItem",
            Command::CLEAR_SESSION_STORAGE => "clearSessionStorage",
            Command::GET_SESSION_STORAGE_SIZE => "getSessionStorageSize",

            // Mobile
            Command::GET_NETWORK_CONNECTION => "getNetworkConnection",
            Command::SET_NETWORK_CONNECTION => "setNetworkConnection",
            Command::CURRENT_CONTEXT_HANDLE => "getCurrentContextHandle",
            Command::CONTEXT_HANDLES => "getContextHandles",
            Command::SWITCH_TO_CONTEXT => "switchToContext",
        }.to_string()
    }
}
